### ISSUE TITLE
crystalStructure unable to initialize from CIF if current working directory is not the directory containing the file

### ISSUE THREAD

**Issue by eandklahn** [eandklahn/phd_repo#5]
**Example of problem**

>>> from cifoperations import cc
>>> dbm = cc.crystalStructure('C:\\Users\\Emil\\Documents\\Uddannelse\\PhD\\pnd_susceptibility\\magnetic_ellipsoids\\DBM.cif')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Emil\Documents\Uddannelse\PhD\pyLIB\cifoperations\cc.py", line 120, in __init__
    self._read_CIF()
  File "C:\Users\Emil\Documents\Uddannelse\PhD\pyLIB\cifoperations\cc.py", line 180, in _read_CIF
    cf = CifFile.ReadCif(self.cifFile)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\CifFile\CifFile_module.py", line 3108, in ReadCif
    permissive=permissive)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\CifFile\StarFile.py", line 2174, in ReadStar
    filestream = urlopen(my_uri)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 549, in _open
    'unknown_open', req)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 1388, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>
>>> import os
>>> os.getcwd()
'C:\\Users\\Emil'
>>>

**Comment by eandklahn** [comment]
I have added functionality that checks whether the file name given to initialize the instance contains a path. If not, then it is assumed that the file is in the current working directory, but if it does, then the function navigates to this folder, reads the CIF and navigates back to the original working directory
